### ISSUE TITLE
Support Netbox 3.1.x

### ISSUE THREAD

**Issue by tsv1991** [sjm-steffann/netbox-ddns#16]
When I try to upgrade Netbox From 3.0.x to 3.1.x, i get error message:

`django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.0.999.`

I think that version v1.2.0 will be great work with Netbox 3.1.x

**Comment by YWatchman** [comment]
Will check compatibility and upgrade, thanks for notifying.

**Comment by martydingo** [comment]
Is there anything preventing a version bump in the relevant `__init__.py`? 

I'm not sure how I feel about maximum versions, I've spent a few hours troubleshooting this issue to find that actually, my version of Netbox is fine, it's the plugin that's preventing netbox from starting due to an arbitary check which doesn't really inform of us of anything but a developer has simply put a limit on versionings in a file and now that versioning doesn't match the newly updated Netbox instance.

**Comment by tsv1991** [comment]
I tested netbox-ddns 1.2.0 with netbox 3.1.2 and did not find any problems.

Temp hack for reproducing this.
`sed -i 's/3.0.999/3.1.999/' /opt/netbox-3.1.2/venv/lib64/python3.9/site-packages/netbox_ddns/__init__.py`

**Comment by YWatchman** [comment]
Version is bumped.
